github: [holtwick] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# custom: https://www.paypal.me/apperdeck # Replace with a single custom sponsorship URL
# patreon: holtwick # Replace with a single Patreon username
